
-- =============================================================================
-- SISTEMA DE MANIFESTO OPERACIONAL (SMO) - VERSÃO 2.5 (WFS & CIA)
-- =============================================================================

-- 1. TABELA DE USUÁRIOS E PERFIS
CREATE TABLE IF NOT EXISTS public."Cadastro_de_Perfil" (
    id bigint primary key generated always as identity,
    "Usuario" text unique not null,
    "Senha" text not null,
    "Nome_Completo" text,
    "sesson_id" text,
    "Session_Data/HR" text,
    created_at timestamptz default now()
);

-- 2. TABELA PRINCIPAL DE MANIFESTOS
CREATE TABLE IF NOT EXISTS public."SMO_Sistema" (
    id bigint primary key generated always as identity,
    "ID_Manifesto" text unique not null,
    "Usuario_Sistema" text,
    "CIA" text not null,
    "Manifesto_Puxado" text,
    "Manifesto_Recebido" text,
    "Representante_CIA" text, 
    "Manifesto_Entregue" text,  
    "Cargas_(IN/H)" integer default 0,
    "Cargas_(IZ)" integer default 0,
    "Status" text default 'Manifesto Recebido',
    "Turno" text,
    "Carimbo_Data/HR" text,
    "Usuario_Ação" text,
    "Usuario_Operação" text,
    "Manifesto_Iniciado" text,
    "Manifesto_Disponivel" text,
    "Manifesto_em_Conferência" text,
    "Manifesto_Pendente" text,
    "Manifesto_Completo" text,
    created_at timestamptz default now(),
    constraint cia_valida check ("CIA" in ('Azul', 'Gol', 'Latam', 'Modern', 'Total'))
);

-- 3. TABELA DE REGISTROS OPERACIONAIS (Log de Eventos)
CREATE TABLE IF NOT EXISTS public."SMO_Operacional" (
    id bigint primary key generated always as identity,
    "ID_Manifesto" text references public."SMO_Sistema"("ID_Manifesto") on delete cascade,
    "Ação" text not null,
    "Usuario" text not null,
    "Cargas_(IN/H)" integer,
    "Cargas_(IZ)" integer,
    "Justificativa" text,
    "Created_At_BR" text,
    created_at timestamptz default now()
);

-- 4. TABELA DE FUNCIONÁRIOS (RELAÇÃO WFS)
CREATE TABLE IF NOT EXISTS public."Funcionarios_WFS" (
    id bigint primary key generated always as identity,
    "Nome" text not null,
    "Cargo" text,
    "Ativo" boolean default true,
    created_at timestamptz default now()
);

-- 5. TABELA DE MÉTRICAS (Performance Monitor)
CREATE TABLE IF NOT EXISTS public."Log_Performance_SMO_Sistema" (
    data date primary key,
    total_requisicoes bigint default 0,
    total_n8n bigint default 0,
    banda_mb numeric default 0,
    usuarios_unicos jsonb default '[]',
    ultima_atualizacao timestamptz,
    total_cadastro integer default 0,
    total_edicao integer default 0,
    total_cancelamento integer default 0,
    total_anulacao integer default 0,
    total_login integer default 0,
    total_logoff integer default 0,
    detalhes_hora jsonb default '{}'
);

-- 6. LIMPEZA E INSERÇÃO DE FUNCIONÁRIOS
TRUNCATE TABLE public."Funcionarios_WFS";

INSERT INTO public."Funcionarios_WFS" ("Nome", "Cargo") VALUES
('EDSON MESQUITA NOGUEIRA', 'GERENTE'),
('LUIZ D''CLAUDIS ARAUJO MARTINS', 'COORDENADOR'),
('MAX MILLER SANTOS DA SILVA', 'TÉCNICO DE SEGURANÇA'),
('ARLISON DE ALMEIDA CARVALHO', 'TÉCNICO DE SEGURANÇA'),
('ADRIANA BASILIO DA SILVA', 'AUX LIMPEZA'),
('RAFAEL ABRAAO DE SOUZA RODRIGUES', 'ANALISTA MELHORIA'),
('RICK CLAUDIO FERREIRA DOS SANTOS', 'AUX'),
('DIEGO NEVES DA SILVA', 'LIDER'),
('HELIO PEREIRA ANDRADE JUNIOR', 'LIDER'),
('PEDRO HEANES PINTO DE SOUZA', 'LIDER'),
('RODRIGO DE ALMEIDA', 'LIDER'),
('GUSTAVO HENRIQUE LIMA DA SILVA', 'LIDER'),
('ANDRE PEREIRA BENTES', 'AUX'),
('IAGO FELIPE MELO GADELHA', 'AUX'),
('MARCELO RODRIGUES PAES', 'AUX'),
('FRANCISCO EDGAR DA SILVA COSTA', 'AUX'),
('EM CONTRATAÇÃO - ARLY', 'AUX'),
('JOSE RAIMUNDO MELO GOMES', 'AUX'),
('WENDEL ALVES BALIEIRO', 'AUX'),
('DENIS COSTA SARMENTO', 'AUX'),
('SEVERINO ALMEIDA DE OLIVEIRA', 'AUX'),
('PEDRO GAMA DE MIRANDA', 'AUX'),
('ADRIANO MIRANDA DE FREITAS', 'AUX'),
('WALTER MONTEIRO PEREIRA', 'AUX'),
('EDUARDO JOSE TORRES FERREIRA', 'AUX'),
('MARCIO DOS SANTOS NASCIMENTO', 'AUX'),
('VANDERLEY DA SILVA TORRES', 'AUX'),
('RUSIVALDO CARDOSO QUEIROZ', 'AUX'),
('DIHEGO CAMPOS FIGUEIREREDO', 'AUX'),
('MARCOS ANTONIO MENDES DE OLIVEIRA', 'AUX'),
('ALYSSON DOS SANTOS PAES', 'AUX'),
('CARLOS EDUARDO MERUOCA RUNA', 'AUX'),
('WILMA APARECIDA PEREIRA DA SILVA BRITO', 'AUX'),
('EDIMARA BRAGA CAMPOS', 'AUX'),
('HERIC MASLOWN DA COSTA AZEVEDO', 'AUX'),
('CARLOS ALBERTO DA SILVA GONÇALVES', 'OP.EQUIP'),
('RAIMUNDO NONATO GONÇALVES P SILVA', 'OP.EQUIP'),
('LEANDRO OLIVEIRA DE SOUZA', 'OP.EQUIP'),
('FRANCISCO FERNANDO CARVALHO DE SOUZA', 'OP.EQUIP'),
('LUCIANO DO VALE DA SILVA SANTOS', 'OP.EQUIP'),
('VANDEMBERG FLORES DAMASCENO', 'OP.EQUIP'),
('ALEXANDRE SILVA DOS ANJOS', 'OP.EQUIP'),
('JACKSON SILVA DOS SANTOS', 'OP.EQUIP'),
('DANIEL MARTINS SARMENTO', 'AUX'),
('PATRICIA GOMES DA SILVA', 'AUX'),
('SIDNEY MARIANO DE SOUZA', 'AUX'),
('LINIKER DE SOUZA PALHETA', 'AUX'),
('EDCARLOS FERNANDES RODRIGUES', 'AUX'),
('RENIER LUCIO DE LIMA', 'AUX'),
('EMERSON ACÁCIO GUEDES', 'AUX'),
('ANTONIO FREDERICO DA SILVA', 'AUX'),
('IZAQUE ALVES DE OLIVEIRA', 'AUX'),
('WALDEMAR FERREIRA DA SILVA', 'AUX'),
('ANSELMO LINHARES DO NASCIMENTO', 'OP.EQUIP'),
('ROBERTO CESAR RAMOS RODRIGUES', 'OP.EQUIP'),
('RAIMUNDO NONATO P. DE S. FILHO', 'OP.EQUIP'),
('LUIZ CARLOS ARAÚJO DA SILVA', 'OP.EQUIP'),
('IVANETE MOURA MEDEIROS', 'AUX'),
('JOSINEY MACHADO DE MELO', 'AUX'),
('ROSANA PRADO MEDEIROS', 'AUX'),
('VANESSA CARDOSO MAQUINÉ', 'OP.EQUIP'),
('MATHEUS LIMA PEREIRA', 'AUX'),
('ADRYA PATRICIA DA SILVA FERREIRA', 'AUX'),
('FRANK NASCIMENTO EVANGELISTA', 'AUX'),
('EMANUEL RAMALHO', 'AUX'),
('FABULO SANTOS DA SILVA', 'AUX'),
('MARCELE GOMES DAS CHAGAS', 'AUX'),
('RAFAEL RIBEIRO AZEVEDO', 'AUX'),
('ALINA DAS NEVES PERINI', 'AUX'),
('LEANDRO DE SOUZA PALHETA', 'AUX'),
('FRANK DOS SANTOS RIBEIRO', 'AUX'),
('ERIMAR COSTA DA SILVA', 'AUX'),
('MARIO JORGE VIANA LOPES JUNIOR', 'AUX'),
('GILMAR FREITAS LALOR', 'AUX'),
('EDSON DE SOUZA OLIVEIRA', 'AUX'),
('ALEXANDRE SOUZA DA COSTA', 'AUX'),
('ANTONIO WILSON DOS SANTOS LEITÃO', 'AUX'),
('ALTAIR DA ENCARNACAO PIRES', 'AUX'),
('FERNANDO HELION ALVES MENDONÇA', 'AUX'),
('FABIO FEITOZA DA SILVA', 'AUX'),
('CAIQUE ROGGER GOMES BARBOSA', 'AUX'),
('PABLO YURI SIMAS DA SILVA', 'AUX'),
('RAIMUNDO ANTONIO ROCHA DE SOUZA', 'AUX'),
('JOÃO PAIXÃO PEREIRA CARRIL', 'AUX'),
('MARCIO RENE LIMA DA SILVA', 'AUX'),
('ARCLEYDSON REIS MOREIRA', 'AUX'),
('MARLON DA SILVA BRAGA', 'AUX'),
('RODRIGO RICARDO COSTA PINHEIRO', 'AUX'),
('JOEL DA SILVA DOS SANTOS JUNIOR', 'AUX'),
('DARLISON SOUSA DE MELO', 'AUX'),
('CARLOS AUGUSTO SOUSA DE MORAES', 'AUX'),
('DAVID DE CASTRO REIS', 'AUX'),
('EDER LINHARES DO NASCIMENTO', 'AUX'),
('ALMIR BARBOSA REIS', 'OP.EQUIP'),
('RUDINEI DA SILVA BARBOSA', 'OP.EQUIP'),
('CLAUDIO DOS SANTOS GUIMARAES FILHO', 'OP.EQUIP'),
('WELLINGTON VEIGA DA SILVA', 'OP.EQUIP'),
('ANTONIO ALMEIDA DE CARVALHO', 'OP.EQUIP'),
('LEANDRO GOMES LACERDA', 'OP.EQUIP'),
('LUCIANO GOMES LACERDA', 'OP.EQUIP'),
('ROGERIO DE SOUZA RIBEIRO', 'OP.EQUIP'),
('OSCAR HAYDEN FILHO', 'AUX'),
('FRANCISCO EVALDO DUARTE MOUTA', 'AUX'),
('JOSE DIDIMO NASCIMENTO', 'AUX'),
('ADEMIR BEZERRA DE MELO', 'AUX'),
('MARCOS DE SOUZA FIGUEIREDO', 'AUX'),
('GILVAN PINTO DE SOUZA', 'AUX'),
('MARIZIO SIQUEIRA DA SILVA', 'OP.EQUIP'),
('JÚLIO CÉSAR FERMIM', 'OP.EQUIP'),
('GLAUCIO MARTINS DA SILVA', 'OP.EQUIP'),
('CLAUDIA CRISTIANE DE ARAUJO FROIS', 'AUX'),
('FRANCISCO JOSINALDO SILVA BARBOSA', 'AUX'),
('HERMANO HERBERT DE CARVALHO LIMA', 'OP.EQUIP'),
('PRISCILA FERNANDA PEREIRA', 'OP.EQUIP'),
('LUCIO FILIPE MARQUES FERREIRA', 'AUX'),
('RICHARDSON QUEIROZ COELHO', 'AUX'),
('SIMONE FERREIRA DE FREITAS', 'AUX'),
('ANDERSON DE CASTRO GURGEL', 'AUX'),
('ALEXSANDRO RODRIGUES BRAGA', 'AUX'),
('RILK EMANUEL ROCHA DO CARMO', 'AUX'),
('WITILAS PINHEIRO MACHADO', 'AUX'),
('ALEX OLIVEIRA DE SOUZA', 'AUX'),
('EDVÃ SERRÃO ANDURAND', 'AUX'),
('NEILSON DE OLIVEIRA JORDÃO', 'AUX'),
('CARLOS GAMA RODRIGUES', 'AUX'),
('ALONSO MACHADO PEREIRA', 'AUX'),
('RAYSSOM FELIPE BATISTA FRAZÃO DA SILVA', 'AUX'),
('FRANCINALDO SILVA MENDES', 'AUX'),
('MARCIO RIBEIRO DA SILVA', 'AUX'),
('FLORIANO DOS SANTOS BERNARDO', 'AUX'),
('AFRANIO SERGIO BATISTA FRAZÃO', 'AUX'),
('JUNIOR DOS SANTOS LIMA', 'AUX'),
('JULIO CEZAR NEVES DE MELO', 'AUX'),
('LUCIANO PEREIRA DOS REIS', 'AUX'),
('THIAGO OLIVEIRA DE SOUZA', 'AUX'),
('ANTONIO ROCHA JUNIOR', 'AUX'),
('ANTONIO FERNANDES DA SILVA', 'AUX'),
('GIVANILDO LEAO DE OLIVEIRA', 'AUX'),
('JOSE RENATO RAMOS DA SILVA', 'AUX'),
('JOSÉ RODRIGUES DE SOUZA', 'OP.EQUIP'),
('MARCIO ALEXANDRE LEMOS BERNARDES', 'OP.EQUIP'),
('AUGUSTO ENCARNAÇÃO DO NASCIMENTO NETO', 'OP.EQUIP'),
('ALEXANDRE SADIM DA SILVA', 'OP.EQUIP'),
('ERMESON COSTA DA SILVA', 'OP.EQUIP'),
('EDIVAN ALVES SARGES', 'OP.EQUIP'),
('JOSE BACELAR FERREIRA', 'OP.EQUIP'),
('FRANCISCO JAMIL DE OLIVEIRA PEREIRA', 'OP.EQUIP'),
('FLAVIO MENDES E SILVA', 'OP.EQUIP'),
('CLEITON ELIAS DE FREITAS SILVA', 'AUX'),
('PAULO SILVANO MENDONÇA MARINHO', 'AUX');

-- 7. DADOS INICIAIS DE ADMIN
INSERT INTO public."Cadastro_de_Perfil" ("Usuario", "Senha", "Nome_Completo") 
VALUES ('Rafael Rodrigues', '123456', 'Rafael Rodrigues')
ON CONFLICT ("Usuario") DO UPDATE SET "Senha" = EXCLUDED."Senha";

-- POLICIES
ALTER TABLE public."SMO_Operacional" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for now" ON public."SMO_Operacional" FOR ALL USING (true) WITH CHECK (true);
